name: Post PRs to Teams

on:
  pull_request:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'ğŸ¤ğŸ» Ready for review')
    steps:
      - name: Notify
        uses: davidwengier/PostAdaptiveCard@v1.0.0
        with:
          webhook-uri: ${{ secrets.TEAMS_PR_WEBHOOK }}